@startuml

skinparam linetype ortho

(*) --> "Recherche d'un place à louer"
"Recherche d'un place à louer" -down-> "Selection d'un place à louer"

if "place disponible" then
  if "Enough money"
    -->[true] "Emettre une reservation"
    "Emettre une reservation" --> (*)
    else 
    -up->[false] "Recherche d'un place à louer"
  endif
  
  
else
  -up->[false] "Recherche d'un place à louer"
endif
@enduml