@startuml

(*) --> "Recherche d'un garage à louer"
"Recherche d'un garage à louer" -down-> "Selection d'un garage à louer"

if "Garage disponible" then
  -->[true] "Emettre une reservation"
  "Emettre une reservation" --> (*)
else
  -up->[false] "Recherche d'un garage à louer"
endif
@enduml